repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=25000"]
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
        exclude: .*/templates
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys", "--no-ensure-ascii"]
        exclude: analysis/.*.ipynb
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.6.1
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [tokenize-rt==3.2.0]
  #       # do not call install-types
  #       args: [--strict, --ignore-missing-imports]
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        args: ["--line-length=120"]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args:
          [
            -m=VERTICAL_HANGING_INDENT,
            --skip=seed/models/__init__.py,
            --filter-files,
          ]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--recursive",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
          ]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--ignore=F401,E402,E501,E731,W503,W504"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        # for now ignoring html, javascript
        # JSON is handled by pretty-format-json
        types_or: [yaml, markdown, css, scss]
