name: Test Build of Python Package

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.x"
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install
      - name: Build package
        run: poetry build
