name: CI

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
        with:
          path: urbanopt-des
      - name: Check if geojson-modelica-translator needs to be checked out
        id: check_gmt
        working-directory: urbanopt-des
        run: |
          if grep -E '^[^#]*geojson-modelica-translator.*path.*=.*"\.\./' pyproject.toml; then
            echo "needs_checkout=true" >> $GITHUB_OUTPUT
          else
            echo "needs_checkout=false" >> $GITHUB_OUTPUT
          fi
      - name: Checkout geojson-modelica-translator
        if: steps.check_gmt.outputs.needs_checkout == 'true'
        uses: actions/checkout@v7
        with:
          repository: urbanopt/geojson-modelica-translator
          ref: develop
          path: geojson-modelica-translator
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: "latest"
      - name: Install dependencies
        working-directory: urbanopt-des
        run: |
          python -m pip install --upgrade pip
          poetry install --no-root
      - name: Run pre-commit
        working-directory: urbanopt-des
        run: poetry run pre-commit run --all-files
      - name: Run mypy
        working-directory: urbanopt-des
        run: poetry run mypy urbanopt_des
      - name: Run pytest
        working-directory: urbanopt-des
        run: poetry run pytest -v --cov-report term-missing --cov
